### ISSUE TITLE
Project rename

### ISSUE THREAD

**Issue by t-b** [byte-physics/igortest#362]
When I started the project in e61779c4 (much more changes, 2012-10-09) I had a much less sophisticated view on testing. And now I think that calling the project "unit" testing framework is plain wrong. You can also write integration and system tests with it.

So how about renaming it to "Igor universal testing framework"? This would keep the abbreviation "IUTF" working ;)

**Comment by Garados007** [comment]
I agree with the rename. The name "**Unit**-Testing-Framework" caused a lot of confusion when I told my friends what I do for a living, as the testing possibilities are very extensive.

Some problems about renaming existing projects:

- every local git clone needs be updated (these are at least all byte-physics member)
    - set the new remote url
    - set the new repository name 
- CI pipeline has to be updated
- update Readme.md, documentation and About section in GitHub
- update other projects which use this project as submodule or dependency (this is at least MIES)
- update the name in official listings (igor exchange, website, ...)

*If I forget something feel free to add it to the list.*

**Comment by t-b** [comment]
Thanks for the list.

We don't need to rename the references to the repo immediately. Github/Gitlab support redirecting from the old name. That is the reason why https://github.com/t-b/igor-pro-coding-conventions still works.

**Comment by Garados007** [comment]
Nice to know. This makes a lot of things easier.

**Comment by t-b** [comment]
Current proposal:

- Name: `Igor Pro Universal Testing Framework`
- Repo: `igortest`
- Abbreviation in the code: `IUTF`
- Module name prefix: `IUTF_`
- Filename prefix: `igortest-XXX`
- Main include file: `igortest.ipf`
  - `unit-testing.ipf` will be kept for now and inclue `igortest.ipf`.
  - RunTest should warn if `unit-testing.ipf` is found in the list of included procedure files
- Fix references in comments and error messages
- Package folder: `root:Packages:igortest:`
- Port `GetInfo` to new naming
- Don't change the name on igorexchange.com

**Comment by MichaelHuth** [comment]
I came up with "Igor Pro Test Bench" but I think the suggestion "Igor Pro Universal Testing Framework" is still better as it is a bit more descriptive.

**Comment by t-b** [comment]
Thanks. I've removed the question label then.

**Comment by Garados007** [comment]
Do I have to update the version tag naming scheme in `create-public-release.sh`?
https://github.com/byte-physics/igor-unit-testing-framework/blob/e6c3d924cc98c8ff25a6f7728577902da59ae739/create-public-release.sh#L6

What should I use?

- `IgorProUniversalTestingFramework-v$newVersion`
- `UniversalTestingFramework-v$newVersion`
- `IgorTest-v$newVersion`

Personally, I like the third option as its short and contain the repo name.

**Comment by t-b** [comment]
> Personally, I like the third option as its short and contain the repo name.

+1 if it is all lowercase as the repo will also be all lower case.
