### ISSUE TITLE
Benefit of pass-by-reference of strings in CHECK_EQUAL_STR

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igortest#363]
Our implementation of CHECK_EQUAL_STR (and all other string assertions) require to use pass-by-reference parameters for string comparison like

```igorpro
	string expected = "abc"
	string value = DoSomething()
	CHECK_EQUAL_STR(expected, value)
```

as pass-by-value parameters would be more appealing.

```igorpro
	CHECK_EQUAL_STR("abc", DoSomething())
```

The implementation for variable and wave comparisons are all pass-by-value. There is no obvious benefit for me to use pass-by-reference for strings as we aren't expected to change the value inside the assertion. There is a small speed difference but this is negligible because we aren't doing a performance test.

```igorpro
Constant MAX_LOOP = 10000000
Constant MAX_STR  =  1000000

Function run()
	string text = ""
	variable i, timer, timeMs
	
	for(i = 0; i < MAX_STR; i++)
		text += "0123456789"
	endfor

	timer = StartMSTimer
	for(i = 0; i < MAX_LOOP; i++)
		PassByReference(text)
	endfor
	timeMs = StopMSTimer(timer) / 1000
	printf "pass-by-reference: %f s\n", timeMs / 1000
	
	timer = StartMSTimer
	for(i = 0; i < MAX_LOOP; i++)
		PassByValue(text)
	endfor
	timeMs = StopMSTimer(timer) / 1000
	printf "pass-by-value:     %f s\n", timeMs / 1000
End

Function PassByReference(string& value)

End

Function PassByValue(string value)

End
```
```
•run()
  pass-by-reference: 0.692850 s
  pass-by-value:     0.813021 s
```

What could we gain if we are using pass-by-value for all assertions? **Simplicity.** The user has to write less code lines, doesn't need to reserve string variables for expected and returned states and don't have to think about when to use pass-by-reference and pass-by-value.

**Comment by t-b** [comment]
The main reason to use pass-by-reference back in 2012 was that this allows to check for null strings.

```igorpro
#include "unit-testing"

Function Test()
	string null, empty = ""
	CHECK_NEQ_STR(null, empty)
End
```

But as it turned out this has little practical value. Especially since we nowadays have the special assertions `CHECK_NULL_STR`/`CHECK_EMPTY_STR`/`CHECK_PROPER_STR`.

If we change it to pass-by-value we should also error out probably if a null string is passed.

**Comment by Garados007** [comment]
I have played with the following code:

```igorpro
#include "unit-testing"

Function run()

	string null, empty = ""
	
	printf "IsNull(&null):  %d, RTE: %d\n", CheckReference(null), GetRTError(1)
	printf "IsNull( null):  %d, RTE: %d\n", CheckValue(null), GetRTError(1)
	printf "IsNull(&empty): %d, RTE: %d\n", CheckReference(empty), GetRTError(1)
	printf "IsNull( empty): %d, RTE: %d\n", CheckValue(empty), GetRTError(1)

End

Function CheckReference(string& value)
	return UTF_Utils#IsNull(value)
End

Function CheckValue(string value)
	return UTF_Utils#IsNull(value)
End
```
```
•run()
  IsNull(&null):  1, RTE: 0
  IsNull( null):  1, RTE: 185
  IsNull(&empty): 0, RTE: 0
  IsNull( empty): 0, RTE: 0
```

It is correctly detecting the null in both cases but for one case we have a pending RTE. If the debugger is enabled it will always be opened without a chance to catch this error at a later point.

The null string handling in Igor is a bit weird as its only throwing an exception if null is used in a pass-by-value context but keeping the original value and continue working fine (1). We can catch this exception and treat this as an assertion error. But the thing is: we never know if this error was thrown because of providing the null value or if this was a user error in a previous statement. Another thing is that `CHECK_EQUAL_STR(null, null)` will always be an assertion error (I except this to be equal).

I can only think of this solution: Make `*_STR(...)` as pass-by-value to simplify the usage in most use cases and if a null was provided treat this as an assertion error. Also add `*_STRREF(...)` variants which use pass-by-reference and can handle null values well without an error. The `*_STRREF` variants are only used when a null value is expected.

> Side Note (1): I am used from other programming languages that pass-by-reference and pass-by-value doesn't change something if a null is allowed or not. There are only runtime errors if I access __the content__ of a null value or compiler errors if I provide a possible null value to an argument that doesn't support null.

**Comment by Garados007** [comment]
WM could also add `string/Z` (like `Wave/Z`) to explicitly allow null values.

**Comment by t-b** [comment]
Conclusion:
- Change `*_EQUAL_STR()`/`*_NE_STR()` to use pass by-value, keep the wrapper function signatures
- Treat RTE 185 due to passed null string as assertion error and clear RTE (WARN/CHECK_REQUIRE)
