### ISSUE TITLE
Allow to randomize the test order in a test suite

### ISSUE THREAD

**Issue by t-b** [byte-physics/igortest#375]
- [x] Needs to use the best PRNG available for each IP version
- [x] RunTest: optional parameters, defaults to off
- [ ] Might be worth looking at InPlaceRandomShuffle in MIES

**Comment by Garados007** [comment]
What are the "best PRNG" for each IP version?

**Comment by t-b** [comment]
`Xoshiro256**` for IP9, lower versions Mersenne Twister. https://prng.di.unimi.it/ has some background on xoshiro.
