### ISSUE TITLE
Bug: Long full function names as wave labels

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igortest#390]
We use at different locations in our code full function names as wave labels to identify their entries faster. This yield to some problems if the full function name is very large and larger than the allowed limit for the current IP version. This happened in #378 and was fixed with 0309a67 (Function Tags: Fix long function name bug, 2023-01-16) for function tags.

At least I found the following waves that use full function names as dimension label:

- `root:Packages:UnitTesting:DataGeneratorWaves` is a wave-reference-wave for the results of the data generators
- `root:Packages:UnitTesting:MMDataState` is a two dimensional value wave for storing test-states of multi-multi-data test cases

**Comment by t-b** [comment]
Use text waves to store the full function name.
