### ISSUE TITLE
Store which lines has been instrumented with a Z_ function to improve Cobertura output

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igortest#414]
Currently, its using InstruData but this is marking all lines between function start and end as instrumented. This is wrong as not all lines are instrumented with a Z_ function like comments, empty lines or variable declarations.

## Dependencies

- [x] ~~PR #396~~ (this issue will be included in PR #396)

**Comment by Garados007** [comment]
@t-b Should the old HTML output also use this data? If so I can remove some old code.

**Comment by t-b** [comment]
@Garados007 Yes I think so. Unless @MichaelHuth objects.

**Comment by MichaelHuth** [comment]
@Garados007 Yes, this makes sense.
