### ISSUE TITLE
Tagging with /// IUTF_EXPECTED_FAILURE results in error due to assertion count 0

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igortest#461]
See test ExportIntoNWB and output in history

![image](https://github.com/byte-physics/igortest/assets/29093275/7f1cc712-867e-4c31-9202-8d0daf0c55e2)

**Comment by Garados007** [comment]
If the assertion count is really 0 then the error message would be something like this:

```
Test case \"%s\" doesn't contain at least one assertion
```

**Comment by Garados007** [comment]
See also PR #377 and Issue #289.

**Comment by MichaelHuth** [comment]
Ok, that was not the correct approach for what I wanted to do.
