### ISSUE TITLE
Add function to unregister IUTFMonitor

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igortest#466]
```igorpro
Function UnRegisterIUTFMonitor()

	DFREF dfr = GetPackageFolder()
	variable/G dfr:BCKG_Registered = 0

	CtrlNamedBackground $BACKGROUNDMONTASK stop
End

```

Sometimes within a test case one could decide to not to do reentry, but reentry is default setup in e.g. TEST_CASE_BEGIN.

**Comment by t-b** [comment]
If we add runtime skip support as suggested in #467, would we automatically unregister? I would think yes.

**Comment by MichaelHuth** [comment]
Yes, skip should unregister automatically. Still I think it would make sense to have that function callable from a TC.

**Comment by t-b** [comment]
Fixed via !469.
