### ISSUE TITLE
TestsCases are counted wrong due to inconsistency in Hooks called

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igortest#473]
At the end of a test suite the TestCaseBegin hook is called again that increases the test case count, but it shouldn't.

There seems to be an issue with calling the internal test case hooks.

To reproduce just e.g. run a single TC from Various.ipf and check the tests="X" in JUnit. It will be 2, but should be 1.

**Comment by Garados007** [comment]
And I haven't looked it up but it could be, that JUnit expects the number of virtual and real test cases combined as well. Each hook is printed as a test case in JUnit and a mismatch in the number of entries and the `test=X` attribute can be considered as invalid JUnit.

**Comment by MichaelHuth** [comment]
Ok, thanks for the explanation.
