### ISSUE TITLE
Integrate compilation testing support

### ISSUE THREAD

**Issue by t-b** [byte-physics/igortest#6]
Present in the MIES project but it should be actually implemented here. License is compatible.

**Comment by t-b** [comment]
And we should also support checking that a test case does not compile, see https://www.wavemetrics.com/comment/19512#comment-19512 for a use case.

**Comment by Garados007** [comment]
I understand the use case but I need more details how to implement and organize this in UTF. My idea is:

- Add somehow a list of files to test. MIES does this using a text file. I think this could be done better. Maybe something like the data generators.
- All files to test are tested in one test case. We use CHECK errors to distinguish them.
- We can use the list of defines but use a matrix instead. We test each combination of defined/undefined symbols. Each combination is one test case.
- All tests for the specified list and defines are located in one single test suite.

We can use a normal test case to initialize the compilation testing. The new test suites/cases are put to the end of the current list of test cases. They are executed after all previous test cases are run.

**Comment by t-b** [comment]
Multi-Multi testcases offer matrix support for multiple string variables. These can be used for ipf files and defines.

MIES' compilation test code is located in https://github.com/AllenInstitute/MIES/tree/main/Packages/tests/Compilation.

Please note that this runs in an IM, as otherwise we can't test if ProcGlobal is compiled or not.

The general use case is that we are doing these compilation checks in a separate test suite and pxp.

We can chat tomorrow afternoon (tuesday) if you need some more insight into that.

**Comment by t-b** [comment]
@Garados007 Please remove the question label if all got resolved las wednesday.

**Comment by Garados007** [comment]
> @Garados007 Please remove the question label if all got resolved las wednesday.

Yes.

**Comment by Garados007** [comment]
@t-b @MichaelHuth I have a problem implementing the compilation check. I have done it similar to MIES:

```igorpro
	Execute/P "INSERTINCLUDE \"" + file + "\""
	Execute/P "variable/G root:Packages:igortest:compilationState = 0x2"
	for(i = 0; i < length; i += 1)
		Execute/P "SetIgorOption poundDefine=" + defines[i]
	endfor
	Execute/P "COMPILEPROCEDURES "
	Execute/P "variable/G root:Packages:igortest:compilationState = " + GetIndependentModuleName() + "#IUTF_Test_Compilation#IsProcGlobalCompiled() ? 0x4 : 0x8"
	Execute/P "DELETEINCLUDE \"" + file + "\""
	for(i = 0; i < length; i += 1)
		Execute/P "SetIgorOption poundUnDefine=" + defines[i]
	endfor
	Execute/P "COMPILEPROCEDURES "
```

I have a problem when `file` is an invalid file which cannot compile. Igor will always show this banner and stop execution:

![grafik](https://user-images.githubusercontent.com/12125053/222456371-bde869a0-3ded-4d1c-847b-4b5c3387e5c4.png)

Is there a way to hide this banner and continue the execution of commands in the command queue?

**Comment by t-b** [comment]
@Garados007 IP9 has `/UNATTENDED`, older versions have ` /CompErrNoDialog`. Both should fix that issue. I don't know if you can pass that to the igorpro command or if we have to adapt the igorpro docker images.
